export const STATUS_ASKING_QUESTION = 'STATUS_ASKING_QUESTION';
export const STATUS_ANSWER_SUBMITTED = 'STATUS_ANSWER_SUBMITTED';
export const STATUS_ANSWER_CORRECT = 'STATUS_ANSWER_CORRECT';
export const STATUS_ANSWER_INCORRECT = 'STATUS_ANSWER_INCORRECT';
